#!/bin/bash

# Read the most recent logins
# Crappy workaround for scope issues (bug?) with pipes
#   http://stackoverflow.com/questions/12819632/why-is-a-variable-changed-within-a-loop-unchanged-outside-the-loop

# Terminal colors
RESET="\e[0m"
BOLD="\e[1m"
RED="\e[31m"
YELLOW="\e[33m"

current_tty=`tty`;

current_session=""
live_sessions=()
last_sessions=()
while read session; do
	read USER TTY HOST TIME <<< $(echo "$session" | awk '{ print $1, $2, $3, $15 }')
	if [[ "$HOST" == ":0" || "$HOST" == ":0.0" ]];then
		# Ignore "local" logins
		continue;
	elif grep -q "still logged in" <<<$session; then
		if [[ "/dev/$TTY" == "$current_tty" ]]; then
			current_session="$session"
		else
			live_sessions+=("$session")
		fi
	else
		dead_sessions+=("$session")
		#break; # NVM. Keep looking for more sessions
	fi
         # recent logins  # junk data at end # Hide the current login
done < <(last -w -F $USER | head -n -2 )     # | tail -n +2 ) 

if [ ${#live_sessions[@]} -gt 0 ]; then
	# ----- CURRENT LOGINS
    echo -e "You are ${BOLD}${RED}still logged in${RESET} on the following machines:"
    for session in "${live_sessions[@]}"
	do
		read USER TTY HOST TIME <<< $(echo "$session" | awk '{ print $1, $2, $3, $15 }')
		LOGIN=$(echo "$session" | awk '{ print $5, $6, $8, $7 }')
		
		since=`since "$LOGIN"`
		echo -e "  ${BOLD}*${RESET} Logged in ${BOLD}$since${RESET} from ${BOLD}${YELLOW}$HOST${RESET} on ${BOLD}${YELLOW}$TTY${RESET}";
	done
	
elif [[ ${#dead_sessions[@]} -eq 0 ]]; then
	# ----- NO CURRENT OR PREVIOUS LOGINS
	echo -e "Welcome, this is your ${BOLD}first time${RESET} logging in!";
	echo -e "If this is not your first time logging in, someone has tampered with the logs!";
	exit 0;
	
else
	# ----- LAST LOGIN
	last_session=${dead_sessions[0]}
	read USER TTY HOST TIME <<< $(echo "$last_session" | awk '{ print $1, $2, $3, $15 }')
	LOGIN=$(echo "$last_session" | awk '{ print $5, $6, $8, $7 }')
	LOGOUT=$(echo "$last_session" | awk '{ print $11, $12, $14, $13 }')
	
	since=`since "$LOGIN"`
	echo -e "Last logged in ${BOLD}$since${RESET} from ${BOLD}${YELLOW}$HOST${RESET}"
	
fi


